- hosts: db
  become: true
  gather_facts: yes
  remote_user: root
  roles:
    - common
    - mysql
    
- hosts: app
  become: true
  gather_facts: yes
  remote_user: root
  roles:
    - common
    - nginx
    - wordpress